class_list = {
    1: {
        'name': 'Cengkeh',
        'description': 'Cengkeh, yang dikenal dengan nama ilmiah Syzygium aromaticum, adalah rempah yang berasal dari Kepulauan Maluku di Indonesia. Rempah ini telah menjadi komoditas penting selama berabad-abad, terutama dalam perdagangan rempah antara Asia dan Eropa. Bunga kering dari pohon cengkeh digunakan sebagai bumbu dalam berbagai masakan di seluruh dunia, termasuk dalam pembuatan rokok kretek khas Indonesia. Cengkeh memiliki rasa yang kuat, manis, dan sedikit pahit dengan aroma yang sangat khas dan hangat, menjadikannya bumbu penting dalam masakan seperti kari, saus, dan minuman hangat seperti teh chai dan glühwein. Selain penggunaannya dalam kuliner, cengkeh juga memiliki banyak manfaat kesehatan. Minyak cengkeh sering digunakan dalam pengobatan tradisional sebagai antiseptik dan untuk meredakan sakit gigi, karena sifat analgesik dan antimikroba yang dimilikinya. Pohon cengkeh dapat tumbuh hingga 20 meter dan memerlukan iklim tropis untuk berkembang dengan baik. Panen cengkeh biasanya dilakukan dengan memetik bunga yang belum mekar dan kemudian mengeringkannya. Sejarah cengkeh juga mencakup masa-masa perebutan kekuasaan dan perdagangan intensif oleh bangsa Eropa, yang menjadikannya salah satu rempah paling berharga di dunia. Hingga kini, cengkeh tetap menjadi komoditas yang penting secara ekonomi dan budaya, terutama di Indonesia.',
        'benefit': 'Cengkeh memiliki beragam manfaat kesehatan yang berharga. Minyak cengkeh, yang kaya akan eugenol, memiliki sifat antimikroba, antijamur, dan analgesik, sehingga sering digunakan untuk meredakan sakit gigi dan infeksi mulut. Cengkeh juga membantu pencernaan dengan meredakan kembung dan mual serta meningkatkan produksi enzim pencernaan. Kandungan antioksidannya yang tinggi melindungi tubuh dari kerusakan akibat radikal bebas, membantu mencegah penyakit kronis dan penuaan dini. Sifat anti-inflamasi cengkeh bermanfaat untuk mengurangi peradangan dan nyeri, sementara aromanya dalam aromaterapi dapat mengurangi stres dan meningkatkan suasana hati.',
        'cientific_name': 'Syzygium Aromaticum',
        'unique_fact': 'Di Indonesia, cengkeh adalah bahan utama dalam pembuatan rokok kretek, yang terkenal dengan aromanya yang khas dan rasa yang unik.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/cengkeh1.jpeg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/cengkeh2.jpg'
    },
    2: {
        'name': 'Jahe',
        'description': 'Jahe, yang dikenal dengan nama ilmiah Zingiber officinale, adalah rempah yang memiliki akar rimpang yang khas dengan rasa pedas dan aroma yang menyengat. Tanaman jahe berasal dari Asia Tenggara, tetapi telah menyebar ke seluruh dunia dan menjadi salah satu rempah yang paling populer dan sering digunakan di berbagai masakan dan minuman. Rimpang jahe sering digunakan sebagai bumbu dalam masakan, memberikan sentuhan pedas dan hangat yang khas pada hidangan seperti kari, sup, dan tumisan. Selain sebagai bumbu, jahe juga memiliki sejumlah manfaat kesehatan yang telah diakui sejak zaman kuno. Sifat antiinflamasi dan antimikroba dari jahe membantu meredakan peradangan dalam tubuh dan melawan infeksi, sementara kandungan antioksidannya membantu melindungi sel-sel tubuh dari kerusakan akibat radikal bebas. Jahe juga dikenal dapat membantu meredakan mual, meningkatkan pencernaan, dan bahkan mengurangi risiko penyakit jantung. Dengan rasa yang khas dan manfaat kesehatannya yang luar biasa, jahe tetap menjadi salah satu rempah yang paling dihargai dan serbaguna dalam dunia kuliner dan pengobatan tradisional.',
        'cientific_name': 'Zingiber Officinale',
        'benefit': 'Jahe memiliki berbagai manfaat kesehatan yang luar biasa. Rempah ini tidak hanya memberikan rasa pedas dan aroma yang khas pada masakan, tetapi juga memiliki sifat antiinflamasi, antimikroba, dan antioksidan yang membantu meredakan peradangan, melawan infeksi, dan melindungi tubuh dari kerusakan sel. Selain itu, jahe juga dikenal dapat meredakan mual, meningkatkan pencernaan, dan bahkan mengurangi risiko penyakit jantung. Dengan berbagai manfaatnya, jahe menjadi bumbu yang sangat dihargai dalam kuliner dan pengobatan tradisional di seluruh dunia.',
        'unique_fact': 'Sejak zaman kuno, jahe telah digunakan untuk meredakan gangguan pencernaan, mengatasi mual, dan bahkan sebagai penawar alami untuk berbagai penyakit.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/jahe1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/jahe2.jpg'
    },
    3: {
        'name': 'Kayu Manis',
        'description': 'Kayu manis, yang berasal dari kulit dalam pohon kayu manis (Cinnamomum verum), adalah rempah yang telah menjadi bagian penting dari budaya kuliner dan pengobatan tradisional di seluruh dunia selama ribuan tahun. Rempah ini dikenal karena aroma manis, pedas, dan hangatnya, serta rasa yang khas. Selain memberikan cita rasa yang kaya pada berbagai hidangan, kayu manis juga memiliki sejumlah manfaat kesehatan yang diakui. Senyawa-senyawa aktif dalam kayu manis, terutama kanela, telah diketahui memiliki sifat antiinflamasi, antimikroba, dan antioksidan yang dapat membantu meningkatkan sistem kekebalan tubuh, mengurangi peradangan, dan memerangi infeksi. Kayu manis juga sering digunakan dalam pengobatan tradisional untuk mengatur kadar gula darah, meningkatkan pencernaan, dan bahkan meredakan ketegangan otot. Dalam beberapa budaya, kayu manis juga dianggap memiliki nilai spiritual dan digunakan dalam upacara adat atau ritual keagamaan. Dengan aroma yang menggoda dan manfaatnya yang beragam, kayu manis tetap menjadi salah satu rempah yang paling dihargai dan sering digunakan di dapur dan dalam pengobatan tradisional di seluruh dunia.',
        'cientific_name': 'Cinnamomum Verum',
        'benefit': 'Kayu manis, selain menjadi bumbu populer dalam berbagai hidangan, juga memiliki sejumlah manfaat kesehatan yang signifikan. Rempah ini kaya akan senyawa antioksidan, seperti kanela, yang telah terbukti memiliki sifat antiinflamasi, antimikroba, dan antidiabetes. Konsumsi kayu manis telah dikaitkan dengan peningkatan kadar gula darah, peningkatan fungsi pencernaan, serta perlindungan terhadap penyakit jantung dan peradangan.',
        'unique_fact': 'Di zaman kuno, kayu manis merupakan barang dagangan yang sangat mahal dan sering digunakan sebagai mata uang atau hadiah untuk raja-raja dan tokoh-tokoh penting.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kayumanis1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kayumanis2.jpg'
    },
    4: {
        'name': 'Kemiri',
        'description': 'Kemiri, juga dikenal sebagai kacang kedelai atau kacang candlenut, adalah buah dari pohon Aleurites moluccanus yang tumbuh di daerah tropis seperti Asia Tenggara dan Pasifik Selatan. Buah ini memiliki cangkang keras yang menyerupai kenari dan bijinya sering digunakan sebagai bumbu dalam masakan tradisional di wilayah-wilayah tersebut. Kemiri memiliki kandungan minyak yang tinggi, yang diekstraksi dari bijinya, dan sering digunakan sebagai bahan utama dalam pembuatan sambal atau bumbu rempah untuk menambahkan rasa kaya dan lembut pada hidangan. Selain itu, minyak kemiri juga sering digunakan dalam perawatan rambut untuk melembutkan dan menguatkan helai-helai rambut. Namun, penting untuk diingat bahwa biji kemiri harus dimasak terlebih dahulu sebelum digunakan dalam masakan, karena dapat mengandung zat yang beracun jika dikonsumsi mentah. Dengan rasa yang unik dan manfaatnya yang beragam dalam masakan dan perawatan kecantikan, kemiri tetap menjadi salah satu bahan penting dalam warisan kuliner dan budaya di Asia Tenggara.',
        'cientific_name': 'Aleurites Moluccanus',
        'benefit': 'Kemiri memiliki sejumlah manfaat yang penting dalam bidang kuliner dan perawatan kecantikan. Biji kemiri kaya akan minyak yang digunakan sebagai bumbu dalam masakan tradisional di Asia Tenggara, memberikan rasa kaya dan lembut pada hidangan. Selain itu, minyak kemiri juga sering digunakan dalam perawatan rambut untuk melembutkan dan menguatkan helai-helai rambut.',
        'unique_fact': 'Biji kemiri sebenarnya mengandung zat yang beracun jika dikonsumsi mentah. Oleh karena itu, biji kemiri selalu dimasak terlebih dahulu sebelum digunakan dalam masakan.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kemiri1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kemiri2.jpg'
    },
    5: {
        'name': 'Kencur',
        'description': 'Kencur, yang juga dikenal dengan nama latin Kaempferia galanga, adalah tanaman herbal yang tumbuh di daerah tropis Asia Tenggara. Rimpang kencur, bagian tanaman yang paling sering digunakan, memiliki aroma yang kuat dan pedas, serta memiliki rasa yang hangat dan segar. Rimpang ini telah lama digunakan dalam pengobatan tradisional sebagai obat herbal untuk meredakan gangguan pencernaan, mual, dan sakit perut. Kencur juga sering digunakan sebagai bumbu dalam masakan untuk memberikan cita rasa yang khas, terutama dalam hidangan kari dan sup. Selain itu, kencur juga memiliki manfaat dalam perawatan kesehatan dan kecantikan, dengan beberapa produk perawatan kulit dan rambut yang mengandung ekstrak kencur untuk sifatnya yang menyegarkan dan tonik. Dengan keunikan rasanya dan manfaatnya yang beragam, kencur tetap menjadi bahan yang sangat dihargai dalam dunia kuliner dan pengobatan tradisional di berbagai budaya di Asia Tenggara.',
        'cientific_name': 'Kaempferia Galanga',
        'benefit': 'Kencur memiliki sejumlah manfaat kesehatan yang luar biasa. Rimpangnya telah lama digunakan dalam pengobatan tradisional untuk meredakan gangguan pencernaan, mengurangi mual, dan mengatasi masalah perut. Senyawa aktif dalam kencur juga diketahui memiliki sifat antiinflamasi dan antimikroba yang membantu memerangi infeksi dan peradangan dalam tubuh. Selain itu, kencur sering digunakan dalam perawatan kecantikan karena sifatnya yang menyegarkan dan tonik untuk kulit dan rambut.',
        'unique_fact': 'Di beberapa daerah, kencur dipercaya memiliki kekuatan magis atau perlindungan mistis dan digunakan dalam upacara adat atau ritual keagamaan.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kencur1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kencur2.jpg'
    },
    6: {
        'name': 'Ketumbar',
        'description': 'Ketumbar, atau Coriandrum sativum, adalah rempah yang berasal dari wilayah selatan Eropa dan Timur Tengah, tetapi telah menyebar ke seluruh dunia sebagai salah satu bahan utama dalam berbagai masakan. Bijinya yang kering digunakan sebagai rempah, sementara daunnya yang segar juga dapat digunakan sebagai herba. Ketumbar memiliki aroma yang khas, segar, dan sedikit manis dengan rasa yang ringan dan rempah-rempah. Rempah ini sering digunakan dalam masakan Asia, Timur Tengah, dan Amerika Latin, serta menjadi komponen penting dalam bumbu masak seperti kari, sambal, dan saus. Di samping memberikan rasa yang unik pada hidangan, ketumbar juga dikenal memiliki sejumlah manfaat kesehatan, termasuk membantu pencernaan, meredakan peradangan, dan meningkatkan kesehatan jantung. Selain itu, ketumbar juga digunakan dalam pengobatan tradisional untuk meredakan gejala gangguan pencernaan dan mengurangi rasa sakit. Dengan keunikan rasanya dan manfaat kesehatannya, ketumbar tetap menjadi salah satu rempah yang paling populer dan sering digunakan di dapur di seluruh dunia.',
        'benefit': 'Ketumbar memiliki sejumlah manfaat kesehatan yang penting. Rempah ini tidak hanya menambahkan cita rasa khas pada masakan, tetapi juga membantu meningkatkan pencernaan, meredakan peradangan, dan meningkatkan kesehatan jantung. Selain itu, ketumbar telah digunakan dalam pengobatan tradisional untuk meredakan gejala gangguan pencernaan dan mengurangi rasa sakit. Dengan beragam manfaatnya, ketumbar menjadi bumbu yang tidak hanya enak tetapi juga menyehatkan.',
        'cientific_name': 'Coriandrum Sativum',
        'unique_fact': 'Ketumbar dapat ditanam di kebun atau dalam pot di rumah dengan relatif mudah, membuatnya menjadi pilihan yang populer bagi mereka yang menyukai masakan rumahan yang segar.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/ketumbar1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/ketumbar2.jpg'
    },
    7: {
        'name': 'Kunyit',
        'description': 'Kunyit, yang memiliki nama ilmiah Curcuma longa, adalah rempah yang berasal dari Asia Selatan dan telah digunakan selama ribuan tahun dalam masakan dan pengobatan tradisional. Rimpang kunyit, bagian tanaman yang paling sering digunakan, memiliki warna kuning-oranye yang khas dan mengandung senyawa aktif kurkumin, yang dikenal memiliki berbagai manfaat kesehatan. Dalam kuliner, kunyit digunakan sebagai bumbu utama dalam berbagai hidangan, memberikan warna cerah dan rasa hangat yang sedikit pahit. Kunyit adalah komponen utama dalam kari dan sering digunakan dalam masakan India, Asia Tenggara, dan Timur Tengah. Selain penggunaannya dalam masakan, kunyit juga digunakan dalam pengobatan Ayurveda dan tradisional Tiongkok untuk mengobati berbagai kondisi seperti peradangan, gangguan pencernaan, dan infeksi. Sifat anti-inflamasi dan antioksidan kurkumin menjadikannya populer sebagai suplemen kesehatan modern. Kunyit juga digunakan dalam berbagai produk kecantikan dan perawatan kulit karena sifatnya yang dapat mencerahkan kulit dan mengatasi jerawat. Secara keseluruhan, kunyit adalah rempah yang kaya manfaat dengan peran penting dalam budaya kuliner dan pengobatan di berbagai belahan dunia.',
        'benefit': 'Kunyit memiliki manfaat kesehatan yang luar biasa karena kandungan kurkuminnya yang memiliki sifat anti-inflamasi dan antioksidan. Ini membantu meredakan peradangan dalam tubuh, mendukung kesehatan pencernaan, dan melindungi jantung. Selain itu, kunyit juga dapat membantu dalam pencegahan kanker dan penyakit Alzheimer, serta memiliki efek positif pada kulit, membantu mencerahkan kulit dan mengatasi jerawat. Dengan beragam manfaat ini, kunyit menjadi bumbu yang tak hanya enak di masakan tetapi juga baik untuk kesehatan secara keseluruhan.',
        'cientific_name': 'Curcuma Longa',
        'unique_fact': 'Di beberapa budaya di Asia Selatan, kunyit digunakan dalam seni tari tradisional sebagai bagian dari ritual dan pemberian makna.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kunyit1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/kunyit2.jpg'
    },
    8: {
        'name': 'Lengkuas',
        'description': 'Lengkuas, yang dikenal juga dengan nama laos atau galangal, adalah tanaman yang tumbuh di daerah tropis Asia Tenggara, khususnya Indonesia, Thailand, dan Malaysia. Rempah ini memiliki akar yang tebal dan beraroma khas yang sering digunakan sebagai bumbu dalam masakan tradisional. Lengkuas memiliki rasa yang pedas, tajam, dan sedikit manis dengan aroma yang segar dan menyegarkan. Rempah ini sering digunakan dalam berbagai hidangan, terutama dalam masakan Thailand dan Indonesia, seperti sup, kari, dan gulai, karena memberikan aroma dan rasa yang unik pada masakan. Selain sebagai bumbu masakan, lengkuas juga telah lama digunakan dalam pengobatan tradisional untuk meredakan gangguan pencernaan, mengatasi mual, dan sebagai tonik untuk meningkatkan kesehatan secara keseluruhan. Dengan kehadirannya yang tak tergantikan dalam masakan Asia Tenggara dan manfaat kesehatannya yang diakui, lengkuas tetap menjadi rempah yang sangat dihargai dalam dunia kuliner dan pengobatan tradisional.',
        'benefit': 'Lengkuas, atau Alpinia galanga, memiliki sejumlah manfaat yang penting untuk kesehatan. Rempah ini tidak hanya memberikan rasa unik pada masakan, tetapi juga memiliki sifat antiinflamasi dan antimikroba yang dapat membantu meredakan peradangan, melawan infeksi, dan meningkatkan sistem kekebalan tubuh. Selain itu, lengkuas juga dikenal dapat membantu dalam meredakan gangguan pencernaan, mengatasi mual, dan bahkan memiliki efek tonik untuk meningkatkan kesehatan secara keseluruhan. Dengan berbagai manfaatnya, lengkuas menjadi salah satu rempah yang penting dalam masakan dan pengobatan tradisional di berbagai budaya di Asia Tenggara.',
        'cientific_name': 'Alpinia Galanga',
        'unique_fact': 'Di beberapa budaya di Asia Tenggara, lengkuas digunakan dalam upacara tradisional dan ritual sebagai simbol kekuatan atau perlindungan.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/lengkuas1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/Lengkuas-fix.jpg'
    },
    9: {
        'name': 'Pala',
        'description': 'Pala, atau Myristica fragrans, adalah rempah yang berasal dari Kepulauan Banda di Maluku, Indonesia. Kepulauan ini dikenal sebagai satu-satunya sumber pala dan fuli (mace) selama berabad-abad sebelum akhirnya menyebar ke berbagai belahan dunia. Biji pala dan fuli merupakan dua bagian yang digunakan dari buah pala, dengan biji pala sering diolah menjadi bubuk untuk bumbu masakan, sementara fuli digunakan sebagai bumbu dengan rasa yang sedikit lebih lembut. Rasa pala yang manis, hangat, dan sedikit pedas dengan aroma kuat yang khas menjadikannya populer dalam berbagai masakan, mulai dari kue, puding, pai, dan saus di masakan Barat hingga kari, sup, dan daging olahan di Timur Tengah dan India. Di Indonesia, pala adalah komponen penting dalam resep tradisional seperti gulai, rendang, dan sup. Pohon pala tumbuh subur di iklim tropis dengan curah hujan yang cukup, dan dapat tumbuh hingga 20 meter, mulai berbuah setelah sekitar 7-9 tahun. Proses panen dilakukan dengan memetik buah yang matang dan memisahkan biji dari fuli. Pala pernah menjadi salah satu rempah paling berharga dan menjadi pusat perebutan kekuasaan bangsa Eropa pada abad ke-16 dan 17. Di masa lalu, biji pala bahkan bernilai tinggi sebagai mata uang dan obat mujarab untuk berbagai penyakit. Dengan keunikan rasa dan manfaat kesehatannya, pala tetap menjadi salah satu rempah yang sangat dihargai di dunia kuliner dan pengobatan tradisional hingga saat ini.',
        'benefit': 'Pala dikenal memiliki berbagai manfaat kesehatan. Pala dapat membantu meredakan gangguan pencernaan dan mual, serta memiliki efek menenangkan yang berguna dalam mengatasi insomnia. Kandungan antioksidannya dapat melawan radikal bebas dalam tubuh. Namun, penting untuk diingat bahwa konsumsi pala dalam jumlah besar bisa menyebabkan halusinasi dan efek psikoaktif lainnya karena senyawa myristicin yang terkandung di dalamnya. Oleh karena itu, penggunaan pala harus dalam jumlah yang wajar.',
        'cientific_name': 'Myristica Fragrans',
        'unique_fact': 'Pala mengandung senyawa myristicin yang, dalam jumlah besar, bisa menyebabkan halusinasi dan efek psikoaktif. Karena itu, penggunaannya harus hati-hati.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/pala1.jpg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/pala2.jpg'
    },
    10: {
        'name': 'Bunga Lawang',
        'description': 'Bunga Lawang, yang juga dikenal sebagai pekak atau star anise, adalah rempah yang berasal dari tanaman Illicium verum dalam keluarga Schisandraceae, banyak ditemukan di Asia Timur dan Tenggara, khususnya Tiongkok dan Vietnam. Rempah ini memiliki bentuk khas menyerupai bintang dengan delapan segmen yang masing-masing mengandung biji kecil dan keras. Warna coklat kemerahan serta aroma dan rasa yang kuat dan manis, mirip dengan licorice atau adas manis, menjadikan Bunga Lawang sebagai bumbu penting dalam berbagai masakan Asia, terutama dalam masakan Tiongkok, Vietnam, dan India. Rempah ini adalah salah satu bahan utama dalam campuran bumbu tradisional Tiongkok, five-spice powder, dan sering digunakan dalam sup, rebusan, dan hidangan daging untuk memberikan aroma dan rasa khas. Selain perannya dalam kuliner, Bunga Lawang juga dikenal dalam pengobatan tradisional karena berbagai manfaat kesehatannya, seperti membantu pencernaan, meredakan batuk, dan mengatasi flu. Bunga Lawang mengandung berbagai senyawa aktif, termasuk anethole yang memberikan aroma dan rasa khas, serta shikimic acid yang digunakan dalam produksi obat antivirus. Penelitian menunjukkan bahwa Bunga Lawang memiliki sifat antivirus, antiinflamasi, dan antijamur, menjadikannya berguna dalam melawan infeksi dan peradangan. ',
        'cientific_name': 'Illicium Verum',
        'benefit': 'Bunga Lawang memiliki berbagai manfaat kesehatan dan kegunaan dalam kehidupan sehari-hari. Dalam hal kesehatan, Bunga Lawang mengandung shikimic acid yang menjadi bahan dasar obat antivirus seperti oseltamivir (Tamiflu) untuk mengobati influenza. Selain itu, Bunga Lawang memiliki sifat antibakteri dan antijamur yang efektif melawan infeksi mikroba dan jamur, serta sifat antiinflamasi yang membantu mengurangi peradangan dalam tubuh. Rempah ini juga bermanfaat untuk kesehatan pencernaan dengan meredakan masalah seperti kembung, sakit perut, dan gangguan pencernaan. Bunga Lawang dapat meredakan gejala batuk dan pilek berkat sifat ekspektorannya, serta membantu mengatur tekanan darah dan meningkatkan kesehatan jantung. Sifat antiseptiknya menjadikannya berguna dalam produk perawatan kulit untuk mencegah infeksi dan menjaga kulit tetap sehat.',
        'unique_fact': 'Tidak semua jenis Bunga Lawang aman dikonsumsi. Japanese star anise (Illicium anisatum) mengandung senyawa yang beracun dan dapat menyebabkan keracunan jika tertelan.',
        'image_url1': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/bunga%20lawang1.jpeg',
        'image_url2': 'https://storage.googleapis.com/rempahpedia-capstoneproject/images/bunga%20lawang2.jpg'
    },
}
